version: 0.2

env:
  parameter-store:
    DOCKERURL: /learn/learn/dockerurl
    DOCKERUSERNAME: /learn/learn/docker/username
    DOCKERPASSWORD: /learn/learn/docker/password  
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo " Starting the build - stage 1"   
  pre_build:
    commands:
      - echo " pre buid phase, installing prerequisites and dependency"
      - yum update -y
      - cd simple-python-app
      - pip install -r requirements.txt
    
  build:
    commands:
      - echo " building the docker image"
#      - sudo yum install docker.io -y
      - docker --version
      - echo "$DOCKERPASSWORD" | docker login -u $DOCKERUSERNAME --password-stdin
      - docker build -t learn:latest .
      - docker push learn:latest 
    
  post_build:
    commands:
      - echo " build is successful"
